services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDesk\CommunityPackages\Akshay\Shopify\:
        resource: '../../*'
        # exclude: '../../{Scripts}'
    