services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    _instanceof:
        Webkul\UVDesk\CoreBundle\Routing\RouterInterface:
            tags: ['uvdesk_core.routing_definitions']
    
    Webkul\UVDesk\ExtensionBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Templates,Package}'
    
    Webkul\UVDesk\ExtensionBundle\EventListener\Console:
        tags:
            - { name: kernel.event_listener, event: console.command }
            - { name: kernel.event_listener, event: console.terminate }
