services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    _instanceof:
        Webkul\UVDesk\CoreBundle\Extensibles\Tickets\SnippetInterface:
            tags: ['uvdesk_core_extensions.ticket_snippet']
        
        Webkul\UVDesk\CoreBundle\Routing\RouterInterface:
            tags: ['uvdesk_core.routing_definitions']
    
    Webkul\UVDesk\ExtensionBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Extension,Package,Templates}'
    
    Webkul\UVDesk\ExtensionBundle\EventListener\Console:
        tags:
            - { name: kernel.event_listener, event: console.command }
            - { name: kernel.event_listener, event: console.terminate }
    
    Webkul\UVDesk\ExtensionBundle\Hooks\ECommerceApplication:
        tags:
            - { name: uvdesk.hooks, type: 'ticket-apps' }
