services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDeskApps\UVDesk\ECommerce\:
        resource: '../../*'
        # exclude: '../../{ECommerce.php}'
    