services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDesk\CommunityExtension\UVDesk\ECommerce\:
        resource: '../../*'
        # exclude: '../../{ECommerce.php}'
    