services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    _instanceof:
        # Ticket Extensible Extensions
        Webkul\UVDesk\CoreBundle\Extensions\Type\TicketWidgetInterface:
            tags: ['uvdesk_core.extension.ticket_widget']
    
    UVDeskApps\UVDesk\Commons\:
        resource: '../../*'
        exclude: '../../{Commons.php}'
    