services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDesk\CommunityExtension\UVDesk\Commons\:
        resource: '../../*'
        # exclude: '../../{Commons.php}'
    