services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDeskApps\UVDesk\Commons\:
        resource: '../../*'
        exclude: '../../{Commons.php}'
    