uvdesk_extensions_applications_dashboard:
    path:     /apps
    controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Dashboard::applications
    defaults: { panelId: 'apps' }

uvdesk_extensions_applications_dashboard_xhr:
    path:     /apps/collection
    controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Dashboard::applicationsXHR
    methods: [GET, POST]

uvdesk_extensions_standalone_application_dashboard:
    path:     /apps/{vendor}/{extension}/{application}
    controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Application::dashboard

uvdesk_extensions_standalone_application_api_endpoint:
    path:     /apps/{vendor}/{extension}/{application}/api
    controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Application::apiEndpointXHR
    methods: [GET, POST]

uvdesk_extensions_standalone_application_callback_endpoint:
    path:     /apps/{vendor}/{extension}/{application}/callback
    controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Application::callbackEndpointXHR
    methods: [GET, POST]

ecommerce_channel_retrieve_order:
    path:     /ticket/{ticketId}/addorder
    controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\ECommerce::fetchOrderDetails
    methods: [POST,PUT]
    requirements:
        ticketId: '\d+'

# # Base application routes
# app_save_application_channel:
#     path:     /apps/{applicationRouteName}/channel/save/{channelId}
#     defaults: { _controller: WebkulAppBundle:Application:createApplicationChannel, channelId: 0 }
#     requirements:
#         channelId: '\d+'

# app_save_application_settings:
#     path:     /apps/{applicationRouteName}/channel/save/settings/{channelId}
#     defaults: { _controller: WebkulAppBundle:Application:saveApplicationChannelSetting, channelId: 0 }
#     requirements:
#         channelId: '\d+'

# app_remove_application_channel:
#     path:     /apps/{applicationRouteName}/channel/remove/{channelId}
#     defaults: { _controller: WebkulAppBundle:Application:removeApplicationChannel, channelId: 0 }

# app_fetch_application_collection:
#     path:     /apps/{applicationRouteName}/collection/fetch
#     controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\ECommerce::fetchOrderDetails
#     # defaults: { _controller: WebkulAppBundle:Application:getApplicationChannelCollectionXhr }

# todo_action:
#     path:     /ticket/todo/{id}
#     controller: Webkul\UVDesk\ExtensionFrameworkBundle\Controller\ECommerce::fetchOrderDetails
#     defaults: { id: 0 }
#     # defaults: { _controller: WebkulTicketBundle:Todo:todoXhr ,id: 0 }

# app_process_application_external_redirect:
#     path:     /apps/{applicationRouteName}/handle/redirect
#     defaults: { _controller: WebkulAppBundle:Application:applicationExternalRedirect }
