services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDesk\CommunityPackages\UVDesk\ShopifyModule\:
        resource: '../../*'
        # exclude: '../../{Shopify.php}'
    