services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDesk\CommunityExtension\UVDesk\ShopifyModule\:
        resource: '../../*'
        # exclude: '../../{Shopify.php}'
    