services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    UVDeskApps\UVDesk\Shopify\:
        resource: '../../*'
        # exclude: '../../{Shopify.php}'
    