services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    _instanceof:
        # Packages
        Webkul\UVDesk\ExtensionBundle\Framework\HelpdeskModuleInterface:
            tags: ['uvdesk_extensions.helpdesk_module']
        
        Webkul\UVDesk\ExtensionBundle\Framework\HelpdeskComponentInterface:
            tags: ['uvdesk_extensions.helpdesk_component']
        
        # Application Extensible Extensions
        Webkul\UVDesk\ExtensionBundle\Extensions\Type\ApplicationInterface:
            tags: ['uvdesk_extensions.extension.application']
        
        # Ticket Extensible Extensions
        Webkul\UVDesk\CoreBundle\Extensions\Type\TicketWidgetInterface:
            tags: ['uvdesk_core.extension.ticket_widget']
    
    UVDeskApps\UVDesk\Shopify\:
        resource: '../../*'
    